export declare const formItemProps: string[];
export declare const tableColumnProps: string[];
export declare const names: {
    optionvalue: string;
    labelname: string;
    valuename: string;
    childrenname: string;
};
export declare const filterDefaultKey = "$default";
export declare const defaultFilterVoidText = "--";
export declare const emptyValue = "empty";
export declare const emptyKey = "$withEmpty";
export declare const resetProp = "$reset";
export declare const submitProp = "$submit";
export declare const deleteProp = "$delete";
export declare const deleteTipProp = "$delete-confirm";
export declare const pushProp = "$push";
export declare const submitEventType = "submitEventType";
export declare const proxyEvents = "proxyEvents";
export declare const tablePageChangeProp = "$page";
export declare const tableSorterType = "sorter";
export declare const tableSelectionProp = "$selection";
export declare const customTypeProp = "$customType";
export declare const changeType = "change";
export declare const clickType = "click";
export declare const defaultPage: {
    pageNo: number;
    pageSize: number;
};
export declare const defaultDebounceWait = 280;
export declare const isRenderComponent = "__isRenderComponent";
export declare const hasNameProp = "__hasNameProp";
